### ISSUE TITLE
Failed to initialize GLFW

### ISSUE THREAD

**Issue by GentlemanHu** [filliptm/ComfyUI_Fill-Nodes#13]
```python
!!! Exception during processing!!! Failed to initialize GLFW
Traceback (most recent call last):
  File "/content/drive/colab_ai/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/content/drive/colab_ai/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/content/drive/colab_ai/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/content/drive/colab_ai/ComfyUI/custom_nodes/ComfyUI_Fill-Nodes/nodes/fl_infinitezoom.py", line 103, in apply_shader
    result_img = self.process_image(img, scale, mirror, mirror_warp, iterations, speed,
  File "/content/drive/colab_ai/ComfyUI/custom_nodes/ComfyUI_Fill-Nodes/nodes/fl_infinitezoom.py", line 124, in process_image
    raise RuntimeError("Failed to initialize GLFW")
RuntimeError: Failed to initialize GLFW

#1 [FL_InfiniteZoom]: 0.03s
Prompt executed in 0.03 seconds
no pending upload
```

**Comment by makeitrad** [comment]
I'm seeing a similar error on Ubuntu 22.04. Would love to use these but not sure openGL and linux play nice together... Any ideas?

```
/home/zvi/miniconda3/envs/comfy2/lib/python3.10/site-packages/glfw/__init__.py:914: GLFWError: (65544) b'X11: The DISPLAY environment variable is missing'
  warnings.warn(message, GLFWError)
!!! Exception during processing!!! Failed to initialize GLFW
Traceback (most recent call last):
  File "/home/zvi/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/zvi/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/zvi/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/zvi/ComfyUI/custom_nodes/ComfyUI_Fill-Nodes/nodes/fl_infinitezoom.py", line 103, in apply_shader
    result_img = self.process_image(img, scale, mirror, mirror_warp, iterations, speed,
  File "/home/zvi/ComfyUI/custom_nodes/ComfyUI_Fill-Nodes/nodes/fl_infinitezoom.py", line 124, in process_image
    raise RuntimeError("Failed to initialize GLFW")
RuntimeError: Failed to initialize GLFW
```

**Comment by filliptm** [comment]
Pushed a bash script to fix this issue. just run the script in the repo directory and it should do the thing
