### ISSUE TITLE
libOpenGL cannot open because it is not found

### ISSUE THREAD

**Issue by dsigmabcn** [filliptm/ComfyUI_Fill-Nodes#16]
Hi, 

In Linux (Runpod Pytorch container), after installing the custom node from the manager, I get this error:

No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
Failed to load library ( 'libOpenGL.so.0' ): libOpenGL.so.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/workspace/ComfyUI/nodes.py", line 1881, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspace/ComfyUI/custom_nodes/ComfyUI_Fill-Nodes/__init__.py", line 20, in <module>
    from .nodes.fl_shader import FL_Shadertoy
  File "/workspace/ComfyUI/custom_nodes/ComfyUI_Fill-Nodes/nodes/fl_shader.py", line 3, in <module>
    import OpenGL.GL as gl
  File "/workspace/ComfyUI/venv/lib/python3.10/site-packages/OpenGL/GL/__init__.py", line 4, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/workspace/ComfyUI/venv/lib/python3.10/site-packages/OpenGL/GL/VERSION/GL_1_1.py", line 14, in <module>
    from OpenGL.raw.GL.VERSION.GL_1_1 import *
  File "/workspace/ComfyUI/venv/lib/python3.10/site-packages/OpenGL/raw/GL/VERSION/GL_1_1.py", line 7, in <module>
    from OpenGL.raw.GL import _errors
  File "/workspace/ComfyUI/venv/lib/python3.10/site-packages/OpenGL/raw/GL/_errors.py", line 4, in <module>
    _error_checker = _ErrorChecker( _p, _p.GL.glGetError )
AttributeError: 'NoneType' object has no attribute 'glGetError'

I can workaround it using:
apt-get install freeglut3 freeglut3-dev

but eventually I get the message: 
No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'

**Comment by KytraScript** [comment]
I ran into this same issue on a runpod server and here is how I solved it:
```
apt-get update
apt-get install libgl1-mesa-dev
```
or this if your environment requires it:
```
sudo apt-get update
sudo apt-get install libgl1-mesa-dev
```

**Comment by RONNYKHALIL** [comment]
> I ran into this same issue on a runpod server and here is how I solved it:
> 
> ```
> apt-get update
> apt-get install libgl1-mesa-dev
> ```
> 
> or this if your environment requires it:
> 
> ```
> sudo apt-get update
> sudo apt-get install libgl1-mesa-dev
> ```

gahhh! hero! thank you!
