### ISSUE TITLE
Cannot install ComfyUI_Fill-Nodes on RunPod (Ubuntu Linux)

### ISSUE THREAD

**Issue by mbac** [filliptm/ComfyUI_Fill-Nodes#31]
Hi,

I'm getting the following error even after using the proposed "fix" in ComfyUI manager:

```
Failed to load library ( 'libOpenGL.so.0' ): libOpenGL.so.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/workspace/ComfyUI/nodes.py", line 1994, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspace/ComfyUI/custom_nodes/ComfyUI_Fill-Nodes/__init__.py", line 16, in <module>
    from .nodes.FL_Shader import FL_Shadertoy
  File "/workspace/ComfyUI/custom_nodes/ComfyUI_Fill-Nodes/nodes/FL_Shader.py", line 3, in <module>
    import OpenGL.GL as gl
  File "/workspace/ComfyUI/venv/lib/python3.11/site-packages/OpenGL/GL/__init__.py", line 4, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/workspace/ComfyUI/venv/lib/python3.11/site-packages/OpenGL/GL/VERSION/GL_1_1.py", line 14, in <module>
    from OpenGL.raw.GL.VERSION.GL_1_1 import *
  File "/workspace/ComfyUI/venv/lib/python3.11/site-packages/OpenGL/raw/GL/VERSION/GL_1_1.py", line 7, in <module>
    from OpenGL.raw.GL import _errors
  File "/workspace/ComfyUI/venv/lib/python3.11/site-packages/OpenGL/raw/GL/_errors.py", line 4, in <module>
    _error_checker = _ErrorChecker( _p, _p.GL.glGetError )
                                        ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'glGetError'

Cannot import /workspace/ComfyUI/custom_nodes/ComfyUI_Fill-Nodes module for custom nodes: 'NoneType' object has no attribute 'glGetError'
```

Edit: then I get this in the installation report:
```
0.4 seconds (IMPORT FAILED): /workspace/ComfyUI/custom_nodes/ComfyUI_Fill-Nodes
```

Other nodes seem to install without issues.

Can you please help?

Thanks…

**Comment by filliptm** [comment]
still working on a fix for this

**Comment by joel-galleri5** [comment]
run these following commands, this is how i fixed it.

`sudo apt-get install libgl1-mesa-glx
sudo apt-get install freeglut3-dev
pip install PyOpenGL PyOpenGL_accelerate`

if you don't have sudo, install it first.

`apt update -y
apt install sudo -y`

**Comment by lshaocheng** [comment]
> still working on a fix for this

Could you please fix this bug as soon as possible? Thank you.

**Comment by filliptm** [comment]
> > still working on a fix for this
> 
> Could you please fix this bug as soon as possible? Thank you.

iv added a bash script in the repo that you can run on your linux machine. This will install everything you need to fix this error

**Comment by lshaocheng** [comment]
> > > still working on a fix for this
> > 
> > 
> > Could you please fix this bug as soon as possible? Thank you.
> 
> iv added a bash script in the repo that you can run on your linux machine. This will install everything you need to fix this error

Thank you very much!

**Comment by yawenzzz** [comment]
> > > still working on a fix for this
> > 
> > 
> > Could you please fix this bug as soon as possible? Thank you.
> 
> iv added a bash script in the repo that you can run on your linux machine. This will install everything you need to fix this error

It works!
