### ISSUE TITLE
Import Failed

### ISSUE THREAD

**Issue by AssassinsLament** [filliptm/ComfyUI_Fill-Nodes#36]
![image](https://github.com/user-attachments/assets/cc7350fd-597a-43b4-ad7e-e6b4d10d9470)

![image](https://github.com/user-attachments/assets/9155b40b-e20c-43e9-a474-bfe30e71ceab)

Started happening after updating all.

**Comment by jasoncow007** [comment]
same problem. install frontend will occur another problem
No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.2\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_Fill-Nodes\__init__.py", line 62, in <module>
    from .nodes.FL_PDFToImage import FL_PDFToImages
  File "D:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_Fill-Nodes\nodes\FL_PDFToImage.py", line 2, in <module>
    import fitz  # PyMuPDF
  File "D:\ComfyUI-aki-v1.2\python\lib\site-packages\fitz\__init__.py", line 1, in <module>
    from frontend import *
  File "D:\ComfyUI-aki-v1.2\python\lib\site-packages\frontend\__init__.py", line 1, in <module>
    from .events import *
  File "D:\ComfyUI-aki-v1.2\python\lib\site-packages\frontend\events\__init__.py", line 1, in <module>
    from .clipboard import *
  File "D:\ComfyUI-aki-v1.2\python\lib\site-packages\frontend\events\clipboard.py", line 2, in <module>
    from ..dom import Event
  File "D:\ComfyUI-aki-v1.2\python\lib\site-packages\frontend\dom.py", line 439, in <module>
    from . import dispatcher
  File "D:\ComfyUI-aki-v1.2\python\lib\site-packages\frontend\dispatcher.py", line 15, in <module>
    from . import config, server
  File "D:\ComfyUI-aki-v1.2\python\lib\site-packages\frontend\server.py", line 24, in <module>
    app.mount(config.STATIC_ROUTE, StaticFiles(directory=config.STATIC_DIRECTORY), name=config.STATIC_NAME)
  File "D:\ComfyUI-aki-v1.2\python\lib\site-packages\starlette\staticfiles.py", line 59, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory 'static/' does not exist

**Comment by MorphicOne** [comment]
This is because fitz was added to the requirements, but fitz is a library unrelated to the PyMuPDF library module of the same name. Having it installed confuses the imports. Run `pip uninstall fitz` and it should fix it. Did for me anyway.

**Comment by filliptm** [comment]
removed fitz from req. thanks guys!

**Comment by nicegamer12** [comment]
> Fitz



> 将 Fitz 从 Req 中删除。谢谢大家！

i don't understand the code,can you tell me exactly how to do it?,
