### ISSUE TITLE
moviepy installed but cannot find moviepy.editor

### ISSUE THREAD

**Issue by LordOfNightmares** [filliptm/ComfyUI_Fill-Nodes#40]
`moviepy` installed but cannot find `moviepy.editor`
```python
[2024-11-22 21:02:06.547] Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Fill-Nodes\__init__.py", line 46, in <module>
    from .nodes.FL_DiscordWebhook import FL_SendToDiscordWebhook
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Fill-Nodes\nodes\FL_DiscordWebhook.py", line 5, in <module>
    from moviepy.editor import ImageSequenceClip
ModuleNotFoundError: No module named 'moviepy.editor'

[2024-11-22 21:02:06.550] Cannot import E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Fill-Nodes module for custom nodes: No module named 'moviepy.editor'
```

**Comment by dimasxp** [comment]
the same problem

**Comment by filliptm** [comment]
fixed by removing the editor and need for movie py

**Comment by techidsk** [comment]
In the latest version, I noticed that the GeminiVideoCaptioner node imports ImageSequenceClip and VideoFileClip, which leads to a failure in loading the node.
