### ISSUE TITLE
No module named 'gdown' "Import Failed" - ComfyUI Desktop & Manager, Custom Nodes Manager - MacOS

### ISSUE THREAD

**Issue by BentJams** [filliptm/ComfyUI_Fill-Nodes#41]
Using ComfyUI Manager I have tried installing, uninstalling, restarting etc but cannot get ComfyUI_Fill-Nodes working. 

Error log:

Traceback (most recent call last):
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/nodes.py", line 2026, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/custom_nodes/ComfyUI_Fill-Nodes/__init__.py", line 84, in <module>
    from .nodes.FL_GoogleDriveDownloader import FL_GoogleDriveDownloader
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/custom_nodes/ComfyUI_Fill-Nodes/nodes/FL_GoogleDriveDownloader.py", line 3, in <module>
    import gdown
ModuleNotFoundError: No module named 'gdown'

Cannot import /Applications/ComfyUI.app/Contents/Resources/ComfyUI/custom_nodes/ComfyUI_Fill-Nodes module for custom nodes: No module named 'gdown'

**Comment by BentJams** [comment]
So I kind of solved this, just by removing any references to gdown or googledrivedownloader in the __init__.py file. Not ideal to remove a function, but at least everything else is working and this is not stopping it now.

**Comment by bingozzzz1** [comment]
I also encountered the same problem, can you tell me how to do it?

**Comment by galactic-plane** [comment]
I did this and it fixed my issue:  D:\pinokio\api\comfy.git\app\env\Scripts\python.exe -m pip install gdown

**Comment by filliptm** [comment]
fixed, added to req.
