### ISSUE TITLE
(IMPORT FAILED): D:\work\stable diffusion\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_Fill-Nodes

### ISSUE THREAD

**Issue by bingozzzz1** [filliptm/ComfyUI_Fill-Nodes#42]
Traceback (most recent call last):
  File "D:\work\stable diffusion\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\nodes.py", line 2027, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\work\stable diffusion\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_Fill-Nodes\__init__.py", line 84, in <module>
    from .nodes.FL_GoogleDriveDownloader import FL_GoogleDriveDownloader
  File "D:\work\stable diffusion\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_Fill-Nodes\nodes\FL_GoogleDriveDownloader.py", line 3, in <module>
    import gdown
ModuleNotFoundError: No module named 'gdown'

**Comment by galactic-plane** [comment]
I did this and it fixed my issue:  D:\pinokio\api\comfy.git\app\env\Scripts\python.exe -m pip install gdown

**Comment by filliptm** [comment]
fixed, added to req.
