### ISSUE TITLE
its weird about font issue -PIL/ImageFont.py", line 257, in __init__     self.font = core.getfont( OSError: cannot open resource

### ISSUE THREAD

**Issue by hanetyb** [filliptm/ComfyUI_Fill-Nodes#43]
Do you have any idea on this issue?

Name: Pillow
Version: 10.0.0
Summary: Python Imaging Library (Fork)
Home-page: https://python-pillow.org

![1733108425784](https://github.com/user-attachments/assets/36a48783-c937-4671-8217-b2c86f37fa55)

OSError: cannot open resource

Prompt executed in 49.17 seconds
got prompt
!!! Exception during processing !!! cannot open resource
Traceback (most recent call last):
  File "/ia/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/ia/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/ia/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/ia/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/ia/ComfyUI/custom_nodes/ComfyUI_Fill-Nodes/nodes/FL_ImageNotes.py", line 28, in add_notes
    result_img = self.add_text_bar(img, text, bar_height, text_size)
  File "/ia/ComfyUI/custom_nodes/ComfyUI_Fill-Nodes/nodes/FL_ImageNotes.py", line 43, in add_text_bar
    font = ImageFont.truetype("arial.ttf", text_size)
  File "/home/allain/anaconda3/envs/allaincf/lib/python3.10/site-packages/PIL/ImageFont.py", line 834, in truetype
    return freetype(font)
  File "/home/allain/anaconda3/envs/allaincf/lib/python3.10/site-packages/PIL/ImageFont.py", line 831, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/home/allain/anaconda3/envs/allaincf/lib/python3.10/site-packages/PIL/ImageFont.py", line 257, in __init__
    self.font = core.getfont(
OSError: cannot open resource

**Comment by hanetyb** [comment]
i fixed it already.  its linux, have to mannually create fonts fold

**Comment by kaosbeat** [comment]
what path do you have to create this folder?
