### ISSUE TITLE
FL_ImageNotes cannot open resource

### ISSUE THREAD

**Issue by gangdeq** [filliptm/ComfyUI_Fill-Nodes#46]
got prompt
!!! Exception during processing !!! cannot open resource
Traceback (most recent call last):
File "/root/ComfyUI/execution.py", line 323, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "/root/ComfyUI/execution.py", line 198, in get_output_data
return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "/root/ComfyUI/execution.py", line 169, in _map_node_over_list
process_inputs(input_dict, i)
File "/root/ComfyUI/execution.py", line 158, in process_inputs
results.append(getattr(obj, func)(**inputs))
File "/root/ComfyUI/custom_nodes/ComfyUI_Fill-Nodes/nodes/FL_ImageNotes.py", line 28, in add_notes
result_img = self.add_text_bar(img, text, bar_height, text_size)
File "/root/ComfyUI/custom_nodes/ComfyUI_Fill-Nodes/nodes/FL_ImageNotes.py", line 43, in add_text_bar
font = ImageFont.truetype("arial.ttf", text_size)
File "/root/ComfyUI/lib/python3.10/site-packages/PIL/ImageFont.py", line 879, in truetype
return freetype(font)
File "/root/ComfyUI/lib/python3.10/site-packages/PIL/ImageFont.py", line 876, in freetype
return FreeTypeFont(font, size, index, encoding, layout_engine)
File "/root/ComfyUI/lib/python3.10/site-packages/PIL/ImageFont.py", line 284, in __init__
self.font = core.getfont(
OSError: cannot open resource

**Comment by EmmanuelMr18** [comment]
https://github.com/filliptm/ComfyUI_Fill-Nodes/pull/54 
I made these changes to fix it, We noticed it too when creating containers in linux
